name: Checks for release

on:
    push:
        branches: ['release']
    pull_request:
        branches: ['release']

jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set host entry
              run: |
                  if [[ ! $(sudo cat /etc/hosts | grep "${APP_HOST}") ]]; then
                    sudo echo "127.0.0.1 dev.${APP_HOST} www.dev.${APP_HOST}" | sudo tee -a /etc/hosts;
                  fi
              env:
                  APP_HOST: genguid.com

            - name: Install node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-${{ env.cache-name }}-
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-

            - name: Set locale
              run: TZ=

            - name: Install dependencies
              run: npm install --no-fund --no-audit

            - name: Run e2e tests
              run: npm run test:e2e:ci

            - name: Run client tests
              run: npm run test:client

            - name: Run core tests
              run: npm run test:core

            - name: Run coverage check
              run: npm run coverage

    run-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Install node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-${{ env.cache-name }}-
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-

            - name: Install dependencies
              run: npm install --no-fund --no-audit

            - name: Run lint check
              run: npm run lint

    run-format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Install node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-${{ env.cache-name }}-
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-

            - name: Install dependencies
              run: npm install --no-fund --no-audit

            - name: Run formatter
              run: npm run format

    check-code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Install node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-${{ env.cache-name }}-
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-

            - name: Install dependencies
              run: npm install --no-fund --no-audit

            - name: Check all
              run: npm run check:all:ci

    # check-performance:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: Checkout repo
    #       uses: actions/checkout@v3

    #     - name: Set host entry
    #       run: |
    #         if [[ ! $(sudo cat /etc/hosts | grep "${APP_HOST}") ]]; then
    #           sudo echo "127.0.0.1 dev.${APP_HOST} www.dev.${APP_HOST}" | sudo tee -a /etc/hosts;
    #         fi
    #       env:
    #         APP_HOST: genguid.com

    #     - name: Install node.js
    #       uses: actions/setup-node@v3
    #       with:
    #         node-version: 16.x

    #     - name: Cache node modules
    #       uses: actions/cache@v3
    #       with:
    #         path: node_modules
    #         key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
    #         restore-keys: |
    #           ${{ runner.OS }}-build-${{ env.cache-name }}-
    #           ${{ runner.OS }}-build-
    #           ${{ runner.OS }}-

    #     - name: Install dependencies
    #       run: npm install --no-fund --no-audit

    #     - run: npm run check:performance
